# Generated by Django 5.1.2 on 2024-12-20 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('tutor', 'Tutor'), ('student', 'Student'), ('both', 'Both')], default='student', max_length=10),
        ),
    ]
