# Generated by Django 5.1.2 on 2024-12-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='languages_learned',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='customuser',
            name='languages_taught',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
