# Generated by Django 5.1.4 on 2025-01-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customuser_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
