# Generated by Django 5.1.4 on 2025-01-04 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_customuser_hourly_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTutorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tutor')),
            ],
        ),
    ]
